apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nodejs-mongo-persistent
    tier: database
  name: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi